parrot = "green parrot"
print(parrot)
print(parrot[0])
print(parrot[3])
print(parrot[-1])
print(parrot[0:6])
print(parrot[:6])
print(parrot[6:])
print(parrot[0:6:2])
print(parrot[0::6])
print("hello " *5)
print("hello " * (5+4))
today = "saturday"
print("day" in today)
print("sat" in today)
print("suppu" in today)
